workspace:
  base: /test
  path: drupal-core-require-dev

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
    - DOCUMENT_ROOT=/test/drupal-core-require-dev

pipeline:
  composer-install-lowest:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
    - /cache:/cache
    commands:
    - composer install --ansi --no-suggest --no-progress
    - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    volumes:
    - /cache:/cache
    commands:
    - composer install --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

matrix:
  COMPOSER_BOUNDARY:
  - lowest
  - highest
